### ISSUE TITLE
LargeInt - does it work?

### ISSUE THREAD

**Issue by frcroth** [Herder-IT-Solutions/HerderBib#87]
It doesn't compile for me, complaining that LargeInt isn't a known identifier

**Comment by ghost** [comment]
another argument for #50 
Cardinals are much more effective, more space than we will need and will work !
(But LargeInts is a Alias for int64 and this compiled before at our try)

**Comment by cnmicha** [comment]
I don't experience any issues running Lazarus v1.6.2. Please check for updates or replace LargeInt with int64.

**Comment by cnmicha** [comment]
@frcroth The 'unit' label is for TDBManagement, 'databse' for TDBConnection.

**Comment by cnmicha** [comment]
Please see [this](https://github.com/Herder-IT-Solutions/HerderBib/issues/50#issuecomment-281313661) comment about #50. @ghgd-mp

**Comment by cnmicha** [comment]
There seem to be some name inconsistencies betweeen LargeInt, LongInt and int64.

**Comment by cnmicha** [comment]
fixed? @frcroth

**Comment by ghost** [comment]
I'm sorry for my many questions.
I looked in your Unit where I see that you now want to use LongInt.
Is this necessary for the sqlite database ?
Because all of your arguments not to use Cardinals in #50 are much worse for LongInt than for Cardinal
LongInts have for us only ste half of the space Cardinals have
It have also a negative Intervall which we will never use.

**Comment by cnmicha** [comment]
Please see [this](https://github.com/Herder-IT-Solutions/HerderBib/issues/50#issuecomment-281313661) updated comment.
